{{- if .Values.global.ingress.nginx.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}-ws
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.global.ingress.websocket.timeout | quote }}
spec:
  ingressClassName: {{ .Values.global.ingress.nginx.className }}
  rules:
    - host: {{ .Values.global.externalHost }}
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: {{ include "appflowy-cloud.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
