{{- if .Values.global.ingress.nginx.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appflowy-web.fullname" . }}
  {{- with .Values.ingress.nginx.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.nginx.className }}
  rules:
    - host: {{ .Values.global.externalHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "appflowy-web.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
